CREATE TABLE products_history (
                                  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                  product_id BIGINT NOT NULL,
                                  guid UUID NOT NULL,
                                  name VARCHAR(100) NOT NULL,
                                  quantity INT NOT NULL,
                                  version INT NOT NULL,
                                  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                                  CONSTRAINT unique_guid_version_history UNIQUE (guid, version),
                                  CONSTRAINT unique_product_id_version_history UNIQUE (product_id, version)
);

CREATE INDEX idx_products_history_guid ON products_history (guid);
CREATE INDEX idx_products_history_version ON products_history (version);
CREATE INDEX idx_products_history_product_id ON products_history (product_id);
